---
# Provisioning a dev box

- name: Configuring Base System
  hosts: local
  tasks:
    - name: Checkout dotfiles
      git: repo=git://github.com/scorpionresponse/dotfiles.git dest=/home/{{ ansible_user_id }}/dotfiles

    - name: Install dotfiles
      shell: /home/{{ ansible_user_id }}/dotfiles/install_dotfiles.sh
