---
# Provisioning a dev box

- name: Configuring Base System
  hosts: local
  sudo: yes
  sudo_user: vagrant
  tasks:
    - name: Enable backports (for shellcheck)
      sudo_user: root
      apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' state=present update_cache=true
      apt_repository: repo='deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' state=present update_cache=true

    - name: apt-get install stuff 
      apt: pkg={{ item }} state=installed update_cache=true
      sudo_user: root
      with_items:
        - build-essential
        - python3
        - python3-pip
        - python3-setuptools
        - shellcheck

    - name: Checkout dotfiles
      git: repo=git://github.com/scorpionresponse/dotfiles.git dest=/home/vagrant/dotfiles accept_hostkey=True

    - name: Make install script executable
      shell: chmod +x /home/vagrant/dotfiles/install_dotfiles.sh

    - name: Install dotfiles
      shell: /home/vagrant/dotfiles/install_dotfiles.sh

    - name: pip install stuff
      pip: name={{ item }} executable=pip3
      sudo_user: root
      with_items:
        - flask
        - requests 
