---
# Provisioning a dev box

- name: Configuring Base System
  hosts: local
  sudo: yes
  sudo_user: vagrant
  tasks:
    - name: Checkout dotfiles
      git: repo=git://github.com/scorpionresponse/dotfiles.git dest=/home/vagrant/dotfiles accept_hostkey=True

    - name: Install dotfiles
      shell: /home/vagrant/dotfiles/install_dotfiles.sh
